# we use only major versions not minor versions because Kompose(the utility for
# converting docker-compose.yml to Kubernetes.yml is updated to support only
# major versions (e.g. 1,2,3,4 ), not minor versions(e.g. 2.1, 3.1, 3.3)
# http://kompose.io/conversion/
version: "3"

services:
    nginx:
        image: nginx:1.13-alpine
        restart: unless-stopped
        ports:
            - "8002:80"
        # mounting index.html in nginx equivalent of /var/www/html
        # index.php? well nginx cannot understand php. we must use php with
        # fastcgi process manager (fpm) for nginx to understand
        depends_on:
            - fpm
#        environment:
#            - NGINX_HOST=localhost:8002
#            - NGINX_PORT=80
#            - API_KEY=1a5c728fc0345a265902ee6771a70ab0
#            - AMPLIFY_IMAGENAME=my-docker-instance-123
        volumes:
#            - ./web:/usr/share/nginx/html
# see more at https://www.digitalocean.com/community/tutorials/how-to-configure-the-nginx-web-server-on-a-virtual-private-server
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

            - ./docker/nginx/logs/:/var/log/nginx/
        command: [nginx-debug, '-g', 'daemon off;']

    fpm:
        image: php:7.1-fpm-alpine3.4
        volumes:
            - .:/server/http
        ports:
            - "9000:9000"
